feat: Partial glTF definition
ambi-robotics/tinygltf pull request #1
Opened 2023-01-11 18:49 UTC by visatish

This PR introduces two key features to support partial glTF definitions. Partial definitions are useful for defining modifications to existing / already-imported glTF-conformant graphics assets. A concrete example is a rendering application that loads assets from some asset library but allows for user-defined modifications to these assets before final rendering, i.e. switching out a specific texture. A natural way to define these would be a partial glTF definition that only defines modifications and any parent properties in the hierarchy.

Key features:

1. Optionally enforce required properties: As-is, the parser will error out when required properties are missing. Partial glTF definitions might omit required properties if they are not changing them. This PR adds an additional `required_properties` flag.
2. Metadata for properties that are actually defined vs. filled in with default values: As-is, the parser will fill in defaults for properties that are not defined but have defaults per-spec. This makes it impossible to disambiguate downstream if a property was defined to be updated or not defined at all. This PR adds an additional `defined_flags` member variable to returned structs that can be compared to associated bitwise flags corresponding to potentially ambiguous properties.

## Note:
This PR branches from https://github.com/syoyo/tinygltf/releases/tag/v2.8.0 - not the latest `release` (although they might be one and the same for now). This is why it's currently marked as draft. Not sure how to handle releases for a private fork. I'd like a way to version internal releases against their public counterpart. I.e. `v2.8.0-ambi` or something of the sort. Open to suggestions here.

2023-05-31 17:56 UTC, bkolligs reviewed
So this would allow us to Parse Hydra gltf from within tiny gltf correct? Let me know once your outstanding TODOs are addressed and I can approve - looks reasonable to me but would like to see unit testing of some form

2023-05-31 17:56 UTC, bkolligs requested changes
So this would allow us to Parse Hydra gltf from within tiny gltf correct? Let me know once your outstanding TODOs are addressed and I can approve - looks reasonable to me but would like to see unit testing of some form

2023-05-31 21:39 UTC, visatish commented
> So this would allow us to Parse Hydra gltf from within tiny gltf correct? Let me know once your outstanding TODOs are addressed and I can approve - looks reasonable to me but would like to see unit testing of some form

@bkolligs that's correct. I've added unit tests :)

2023-06-01 17:01 UTC, bkolligs approved these changes

2023-06-01 17:11 UTC, merged